# Nome da Actions:
name: Snake Game

# Controlador do tempo que será feita a atualização dos arquivos.
on:
  schedule:
    # Será atualizado a cada 5 horas.
    - cron: "0 */5 * * *"
  # Permite executar manualmente na aba Actions (para testes).
  workflow_dispatch:

# Regras
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Faz checkout do repositório
      - uses: actions/checkout@v3

      # Gera os arquivos da cobrinha
      - uses: Platane/snk@v3
        id: snake-gif
        with:
          github_user_name: joaodanielkm
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake.gif

      # Publica os arquivos na branch "output"
      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
