name: Snake Game

on:
  schedule:
    # Atualiza a cada 5 horas
    - cron: "0 */5 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout do repositório
      - uses: actions/checkout@v3

      # Gera os arquivos da cobrinha
      - uses: Platane/snk@v3
        with:
          github_user_name: joaodanielkm
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake.gif
             # Personalização de cores
              color_snake: "#39FF14"        # verde neon da cobrinha
              color_dots: "#1b1f23,#2f363d" # cores dos quadradinhos (fundo escuro do GitHub)

      # Publica os arquivos na branch "output"
      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
